### ISSUE TITLE
Algunas mejoras a la pagina.

### ISSUE THREAD

**Issue by fetobanana** [Allavaz/iossa-stats#16]
~~Las selecciones están incluidas en la T3, pero deberían tener su categoría aparte de los clubes~~ y las competencias deberían renombrarse a Copa América 2019 y Copa del Sur 2019.

Se debería agregar una categoría a todos los selectores para separar 5v5 y 6v6, es decir, que la categoría 5v5 muestre de la T0 a la T4 y la 6v6 muestre de la T5 a la T7

Y algunas competencias de clubes también debería renombrarse

- Liga D1 Temporada 2 a Liga D1 T2
- Liga D2 Temporada 1 a Liga D2 T2  
- Copa Master 2019 a Copa Master T2
- Recopa Master 2019 a Recopa Master T2

**Comment by fetobanana** [comment]
Las selecciones ya tienen su propia categoria.

**Comment by Allavaz** [comment]
Las siguientes competencias fueron renombradas en 088ce64:
> 
> * Liga D1 Temporada 2 a Liga D1 T2
> * Liga D2 Temporada 1 a Liga D2 T2
> * Copa Master 2019 a Copa Master T2
> * Recopa Master 2019 a Recopa Master T2
